// src/app/interview/page.tsx

'use client';

import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowLeft, Play, Settings2 } from 'lucide-react';
import { CATEGORY_METADATA } from '@/lib/constants/categories';
import type { QuestionCategory, Difficulty, InterviewMode } from '@/types';

export default function InterviewSetupPage() {
  const router = useRouter();
  const [selectedCategories, setSelectedCategories] = useState<QuestionCategory[]>([]);
  const [difficulty, setDifficulty] = useState<Difficulty>('mid');
  const [mode, setMode] = useState<InterviewMode>('mixed');
  const [maxQuestions, setMaxQuestions] = useState(5);

  const handleCategoryToggle = (category: QuestionCategory) => {
    setSelectedCategories(prev => 
      prev.includes(category)
        ? prev.filter(c => c !== category)
        : [...prev, category]
    );
  };

  const handleStartInterview = () => {
    // Create session and navigate
    const params = new URLSearchParams({
      categories: selectedCategories.join(','),
      difficulty,
      mode,
      maxQuestions: maxQuestions.toString(),
    });
    router.push(`/interview/session?${params.toString()}`);
  };

  return (
    <div className="min-h-screen">
      {/* Header */}
      <header className="border-b">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link 
              href="/" 
              className="p-2 rounded-lg hover:bg-accent transition-colors"
            >
              <ArrowLeft className="w-5 h-5" />
            </Link>
            <div>
              <h1 className="font-semibold text-lg">Mock Interview</h1>
              <p className="text-sm text-muted-foreground">Configure your session</p>
            </div>
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 py-8 max-w-3xl">
        {/* Category Selection */}
        <section className="mb-8">
          <h2 className="text-lg font-semibold mb-4 flex items-center gap-2">
            <Settings2 className="w-5 h-5" />
            Select Topics
          </h2>
          <p className="text-muted-foreground mb-4">
            Choose the categories you want to focus on. Leave empty for all topics.
          </p>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
            {Object.values(CATEGORY_METADATA).map((category) => (
              <button
                key={category.slug}
                onClick={() => handleCategoryToggle(category.slug)}
                className={`p-3 rounded-lg border text-left transition-all ${
                  selectedCategories.includes(category.slug)
                    ? 'border-primary bg-primary/5'
                    : 'hover:border-muted-foreground/50'
                }`}
              >
                <div className="flex items-center gap-2">
                  <div className={`w-8 h-8 rounded ${category.color} flex items-center justify-center`}>
                    <span className="text-white text-sm">
                      {getCategoryEmoji(category.slug)}
                    </span>
                  </div>
                  <span className="font-medium text-sm">{category.name}</span>
                </div>
              </button>
            ))}
          </div>
        </section>

        {/* Difficulty Selection */}
        <section className="mb-8">
          <h2 className="text-lg font-semibold mb-4">Difficulty Level</h2>
          <div className="flex gap-3">
            {(['junior', 'mid', 'senior'] as Difficulty[]).map((level) => (
              <button
                key={level}
                onClick={() => setDifficulty(level)}
                className={`px-4 py-2 rounded-lg border capitalize transition-all ${
                  difficulty === level
                    ? 'border-primary bg-primary/5'
                    : 'hover:border-muted-foreground/50'
                }`}
              >
                {level === 'mid' ? 'Mid-Level' : level}
              </button>
            ))}
          </div>
        </section>

        {/* Mode Selection */}
        <section className="mb-8">
          <h2 className="text-lg font-semibold mb-4">Question Source</h2>
          <div className="space-y-3">
            {([
              { value: 'seed-only', label: 'Curated Questions', desc: 'Use pre-written high-quality questions' },
              { value: 'ai-generated', label: 'AI Generated', desc: 'Fresh questions generated by AI' },
              { value: 'mixed', label: 'Mixed', desc: 'Combination of curated and AI questions' },
            ] as { value: InterviewMode; label: string; desc: string }[]).map((option) => (
              <button
                key={option.value}
                onClick={() => setMode(option.value)}
                className={`w-full p-4 rounded-lg border text-left transition-all ${
                  mode === option.value
                    ? 'border-primary bg-primary/5'
                    : 'hover:border-muted-foreground/50'
                }`}
              >
                <div className="font-medium">{option.label}</div>
                <div className="text-sm text-muted-foreground">{option.desc}</div>
              </button>
            ))}
          </div>
        </section>

        {/* Question Count */}
        <section className="mb-8">
          <h2 className="text-lg font-semibold mb-4">Number of Questions</h2>
          <div className="flex gap-3">
            {[3, 5, 10].map((count) => (
              <button
                key={count}
                onClick={() => setMaxQuestions(count)}
                className={`px-4 py-2 rounded-lg border transition-all ${
                  maxQuestions === count
                    ? 'border-primary bg-primary/5'
                    : 'hover:border-muted-foreground/50'
                }`}
              >
                {count} questions
              </button>
            ))}
          </div>
        </section>

        {/* Start Button */}
        <button
          onClick={handleStartInterview}
          className="w-full py-4 rounded-lg bg-primary text-primary-foreground font-medium flex items-center justify-center gap-2 hover:bg-primary/90 transition-colors"
        >
          <Play className="w-5 h-5" />
          Start Interview
        </button>
      </main>
    </div>
  );
}

function getCategoryEmoji(slug: string): string {
  const emojiMap: Record<string, string> = {
    'system-design': '🏗️',
    'caching-memoization': '💾',
    'bundle-tree-shaking': '📦',
    'security-auth': '🔒',
    'feature-flags': '🚩',
    'css-layout': '🎨',
    'js-event-loop': '🔄',
    'accessibility': '♿',
    'react-internals': '⚛️',
  };
  return emojiMap[slug] || '📚';
}
