// src/types/question.types.ts

/**
 * Branded type pattern for type-safe IDs
 * Prevents accidental mixing of different ID types
 */
declare const __brand: unique symbol;
type Brand<T, B> = T & { [__brand]: B };

export type QuestionId = Brand<string, 'QuestionId'>;
export type CategoryId = Brand<string, 'CategoryId'>;

/**
 * Helper functions for creating branded IDs
 */
export const createQuestionId = (id: string): QuestionId => id as QuestionId;
export const createCategoryId = (id: string): CategoryId => id as CategoryId;

/**
 * Question categories - const assertion for literal types and tree-shaking
 */
export const QUESTION_CATEGORIES = {
  SYSTEM_DESIGN: 'system-design',
  CACHING_MEMOIZATION: 'caching-memoization',
  BUNDLE_TREE_SHAKING: 'bundle-tree-shaking',
  SECURITY_AUTH: 'security-auth',
  FEATURE_FLAGS: 'feature-flags',
  CSS_LAYOUT: 'css-layout',
  JS_EVENT_LOOP: 'js-event-loop',
  ACCESSIBILITY: 'accessibility',
  REACT_INTERNALS: 'react-internals',
} as const;

export type QuestionCategory = typeof QUESTION_CATEGORIES[keyof typeof QUESTION_CATEGORIES];

/**
 * Category metadata for UI display
 */
export interface CategoryMetadata {
  id: CategoryId;
  slug: QuestionCategory;
  name: string;
  description: string;
  icon: string; // Lucide icon name
  color: string; // Tailwind color class
}

/**
 * Difficulty levels matching typical interview progression
 */
export type Difficulty = 'junior' | 'mid' | 'senior';

/**
 * Question source tracking - useful for attribution and filtering
 */
export type QuestionSource =
  | 'seed' // Pre-populated high-quality questions
  | 'ai-generated' // Generated by Kimi K2
  | 'user-created'; // User-added questions

/**
 * Core Question interface
 * Designed to support both flashcard study and interview simulation
 */
export interface Question {
  id: QuestionId;
  category: QuestionCategory;
  difficulty: Difficulty;

  /**
   * The actual interview question
   * Should be phrased as an interviewer would ask it
   */
  question: string;

  /**
   * Comprehensive model answer in Markdown format
   * Includes code examples, explanations, and edge cases
   */
  answer: string;

  /**
   * Bullet points of what interviewers are looking for
   * Used by AI to evaluate responses and for self-assessment
   */
  keyPoints: string[];

  /**
   * Follow-up questions an interviewer might ask
   * Used by the interview simulator for deeper exploration
   */
  followUpQuestions: string[];

  /**
   * Related topic slugs for spaced repetition grouping
   * Helps surface related concepts during study
   */
  relatedTopics: string[];

  /**
   * Where this question came from / inspiration
   */
  source: QuestionSource;

  /**
   * Optional: Company or context where this question is common
   */
  commonAt?: string[];

  /**
   * Timestamps for tracking
   */
  createdAt: string; // ISO date string
  updatedAt: string; // ISO date string

  /**
   * Soft delete support
   */
  isArchived: boolean;
}

/**
 * Input type for creating new questions (omits computed fields)
 */
export type CreateQuestionInput = Omit<
  Question,
  'id' | 'createdAt' | 'updatedAt' | 'isArchived'
>;

/**
 * Input type for updating questions (all fields optional except id)
 */
export type UpdateQuestionInput = Partial<Omit<Question, 'id'>> & {
  id: QuestionId;
};

/**
 * Question with computed display properties
 * Used for UI rendering
 */
export interface QuestionWithMeta extends Question {
  categoryMeta: CategoryMetadata;
  difficultyLabel: string;
  estimatedTime: number; // minutes
}

/**
 * Filter options for querying questions
 */
export interface QuestionFilters {
  categories?: QuestionCategory[];
  difficulties?: Difficulty[];
  sources?: QuestionSource[];
  searchQuery?: string;
  includeArchived?: boolean;
}

/**
 * Sort options for question lists
 */
export type QuestionSortField = 'createdAt' | 'updatedAt' | 'difficulty' | 'category';
export type SortDirection = 'asc' | 'desc';

export interface QuestionSortOptions {
  field: QuestionSortField;
  direction: SortDirection;
}
